### ISSUE TITLE
keyring problem

### ISSUE THREAD

**Issue by wistarine** [3v1n0/libfprint#20]
thx a lot..... but there is a issue:
(ubuntu 20.04.1   thinkpad x1c 2017 fingerprint reader:138a:0097)

follow the guide,  one step by step , finally ,it worked..    

but when i login the system at the  first time or reboot system , after auth fingerprint to login system ,  then system shows “input  keyring.... something like this''  and i must type my passwd again..
how do i fix this issue?  i wanna just use fingerprint to login the system without type any passwd......

**Comment by 3v1n0** [comment]
This is unfortunately not possible as the keyring would still need to get a passphrase to be unlocked, a part that by design the Ubuntu security team wants the user to input a password to unlock its passwords wallet, but there are also some technical issues that are hard to solve (given that we can't hide the token anywhere safely)

Read more at https://gitlab.gnome.org/GNOME/gdm/-/issues/613 (and other similar issues you can google about)

**Comment by wistarine** [comment]
> This is unfortunately not possible as the keyring would still need to get a passphrase to be unlocked, a part that by design the Ubuntu security team wants the user to input a password to unlock its passwords wallet, but there are also some technical issues that are hard to solve (given that we can't hide the token anywhere safely)
> 
> Read more at https://gitlab.gnome.org/GNOME/gdm/-/issues/613 (and other similar issues you can google about)

thx man.......
